name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Access Places Key
        env:
            APOD_API_KEY: ${{ secrets.PLACES_API_KEY }}
        run: echo PLACES_API_KEY=\"$PLACES_API_KEY\" >> ./BobsLittleFreeLibrary/local.properties

      - name: Access Maps Key
        env:
            APOD_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: echo MAPS_API_KEY=\"$MAPS_API_KEY\" >> ./BobsLittleFreeLibrary/local.properties

      - name: Access Books Key
        env:
            APOD_API_KEY: ${{ secrets.BOOKS_API_KEY }}
        run: echo BOOKS_API_KEY=\"$BOOKS_API_KEY\" >> ./BobsLittleFreeLibrary/local.properties

      - name: Run Unit tests
        working-directory: ./BobsLittleFreeLibrary
        run: bash ./gradlew BookTest

      - name: Build Project
        working-directory: ./BobsLittleFreeLibrary
        run: bash ./gradlew assemble
