name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Print contents in current directory
      run: ls -la
    - name: Make gradlew executable
      run: chmod +x ./BobsLittleFreeLibrary/gradlew
    - name: Build with Gradle
      run: ./BobsLittleFreeLibrary/gradlew build
    - name: Get Gradle Tasks
      run: ./BobsLittleFreeLibrary/gradlew tasks --stacktrace
    - name: Run Unit tests
      run: ./BobsLittleFreeLibrary/gradlew BookTest --stacktrace
